### ISSUE TITLE
Declarations inside declarations do not inherit prefix 

### ISSUE THREAD

**Issue by violetastcs** [wotpp/wotpp#59]
```wpp
prefix "x/" {
    let y {
        let z "Hello"
        ""
    }
}
```
defines `z` when `x/y` is called instead of `x/z`

**Comment by violetastcs** [comment]
Closing as it was discussed in the Discord that this will not be fixed.

**Comment by Jackojc** [comment]
Just to add to this, the reason it won't be fixed (for the short term at least) is because the problem ends up being quite complicated to solve. We basically have 2 options:
1. Have a separate, static pass before evaluation that assigns the prefix to everything in a nested way
2. Attach metadata to functions, blocks and prefixes which is handled dynamically (very messy)
Neither of these are perfect solutions and it's fairly easy to discover cases where both break.
